<?php
require dirname(__DIR__).'/includes/bootstrap.php';require_admin();
$id=(string)($_GET['id']??'');$s=$db->prepare('SELECT * FROM body_reports WHERE public_id=?');$s->execute([$id]);$r=$s->fetch();if(!$r){exit('Not found');}
$photos=report_photos($db,(int)$r['id']);$title='Case Report '.$r['public_id'];require dirname(__DIR__).'/includes/admin_header.php';
?>
<div class="card"><div style="display:flex;justify-content:space-between;gap:15px"><div><h1>Dead Body Mapping – Case Report</h1><div class="case-id"><?=e($r['public_id'])?></div></div><button class="btn no-print" onclick="window.print()">Print</button></div><hr>
<div class="grid grid-2"><div><p><strong>Type:</strong> <?=e(body_type_labels()[$r['body_type']]??$r['body_type'])?><br><strong>Status:</strong> <?=e(status_labels()[$r['status']]??$r['status'])?><br><strong>Reported:</strong> <?=e($r['created_at'])?><br><strong>GPS:</strong> <?=e($r['latitude'])?>, <?=e($r['longitude'])?><br><strong>Source/accuracy:</strong> <?=e($r['location_source'])?> / <?=e((string)$r['gps_accuracy'])?> m<br><strong>Location:</strong> <?=e($r['location_text'])?><br><strong>Landmark:</strong> <?=e($r['landmark'])?></p></div><div><p><strong>Reporter:</strong> <?=e($r['reporter_name'])?><br><strong>Phone:</strong> <?=e($r['reporter_phone'])?><br><strong>Organization:</strong> <?=e($r['reporter_organization'])?><br><strong>Police informed:</strong> <?=$r['police_informed']?'Yes':'No'?><br><strong>Police unit:</strong> <?=e($r['police_unit'])?><br><strong>Police reference:</strong> <?=e($r['police_reference'])?></p></div></div>
<h3>Response</h3><div class="grid grid-2"><p><strong>Confirmed:</strong> <?=e($r['confirmed_at'])?><br><strong>Team:</strong> <?=e($r['rescue_team_name'])?><br><strong>Team contact:</strong> <?=e($r['rescue_team_contact'])?><br><strong>Dispatched:</strong> <?=e($r['team_dispatched_at'])?></p><p><strong>Recovered by:</strong> <?=e($r['recovered_by'])?><br><strong>Recovered:</strong> <?=e($r['recovered_at'])?><br><strong>Destination:</strong> <?=e($r['destination_type'].' '.$r['destination_name'])?><br><strong>Mortuary Bag:</strong> <?=e($r['mortuary_bag_no'])?><br><strong>Muchulka:</strong> <?=e($r['muchulka_reference'])?></p></div>
<h3>Description</h3><p><?=nl2br(e($r['description']))?></p>
<h3>Identification</h3><p><strong>Gender:</strong> <?=e($r['approx_gender'])?> &nbsp; <strong>Age:</strong> <?=e((string)$r['approx_age_min'])?>–<?=e((string)$r['approx_age_max'])?><br><strong>Condition:</strong> <?=e($r['body_condition'])?><br><strong>Clothes:</strong> <?=nl2br(e($r['clothes']))?><br><strong>Marks:</strong> <?=nl2br(e($r['identifying_marks']))?><br><strong>Documents:</strong> <?=nl2br(e($r['documents_found']))?><br><strong>Identified as:</strong> <?=e($r['identified_name'])?></p>
<?php if($r['body_type']==='animal'):?>
<h3>Animal Carcass Assessment</h3>
<p><strong>Observed:</strong> <?=e($r['observed_at'])?> &nbsp; <strong>Weather:</strong> <?=e(weather_condition_labels()[$r['weather_condition']]??$r['weather_condition'])?><br>
<strong>Species:</strong> <?=e(animal_species_labels()[$r['animal_species']]??$r['animal_species'])?><?=$r['animal_species']==='other'?' — '.e($r['animal_species_other']):''?><br>
<strong>Size:</strong> <?=e(estimated_size_labels()[$r['estimated_size']]??$r['estimated_size'])?> &nbsp; <strong>Count:</strong> <?=e((string)$r['carcass_count'])?> &nbsp; <strong>Decomposition:</strong> <?=e(decomposition_state_labels()[$r['decomposition_state']]??$r['decomposition_state'])?><br>
<strong>Distance from water:</strong> <?=e(distance_water_source_labels()[$r['distance_water_source']]??$r['distance_water_source'])?> &nbsp; <strong>Distance from settlement:</strong> <?=e(distance_settlement_labels()[$r['distance_settlement']]??$r['distance_settlement'])?><br>
<strong>Proposed disposal:</strong> <?=e(disposal_method_labels()[$r['disposal_method']]??$r['disposal_method'])?><?=$r['disposal_method_notes']?' — '.e($r['disposal_method_notes']):''?><br>
<strong>Equipment needed:</strong> <?=e(implode(', ',array_map(fn($k)=>equipment_needed_labels()[$k]??$k,array_filter(explode(',',(string)$r['equipment_needed'])))))?><?=$r['equipment_needed_other']?' + '.e($r['equipment_needed_other']):''?><br>
<strong>Disinfection materials:</strong> <?=e(implode(', ',array_map(fn($k)=>disinfection_materials_labels()[$k]??$k,array_filter(explode(',',(string)$r['disinfection_materials'])))))?></p>
<?php endif;?>
<h3>Burial / final handling</h3><p><strong>Date:</strong> <?=e($r['buried_at'])?><br><strong>Location:</strong> <?=e($r['burial_location'])?><br><strong>GPS:</strong> <?=e((string)$r['burial_latitude'])?>, <?=e((string)$r['burial_longitude'])?><br><strong>Handled by:</strong> <?=e($r['burial_by'])?><br><?=nl2br(e($r['burial_notes']))?></p>
<h3>Closure / correction</h3><p><strong>Closed:</strong> <?=e($r['closed_at'])?><br><strong>Reason:</strong> <?=e($r['closure_reason'])?><br><strong>False/incorrect report notes:</strong> <?=nl2br(e($r['false_report_details']))?></p>
<?php if($photos):?><h3>Restricted photos</h3><div class="photo-grid"><?php foreach($photos as $p):?><img src="../photo.php?id=<?=e((string)$p['id'])?>" alt="Restricted evidence"><?php endforeach;?></div><?php endif;?></div>
<?php require dirname(__DIR__).'/includes/admin_footer.php'; ?>
